### ISSUE TITLE
syntax error on Ubuntu

### ISSUE THREAD

**Issue by mergwyn** [zfsonlinux/zfs-auto-snapshot#108]
A recent commit has introduced an error (at least on Ubuntu 18.04) on line 227:
`if [ "$(uname)" == "Darwin" ]; then`
The error is:
`/usr/local/bin/zfs-auto-snapshot: 227: [: Linux: unexpected operator`

The '==' seems to be the problem.

**Comment by theAkito** [comment]
Issue can be closed.
