### ISSUE TITLE
Add SuSE integration notes

### ISSUE THREAD

**Issue by dajhorn** [zfsonlinux/zfs-auto-snapshot#28]
From: https://groups.google.com/a/zfsonlinux.org/d/msg/zfs-discuss/nW4vODLQszs/v7h5w7rYtbQJ

On Wed, Jul 16, 2014 at 2:40 AM,  <gyro@zeta-soft.com> wrote:
> So I installed zfs-auto-snapshot on my openSuSE 13.1 system, and it didn't
> work -- I got the 'frequent' snapshots, but not the 'hourly' etc.
>
> It took a bit of fiddling to track down the reason.  SuSE's version of
> 'run-crons', which is what invokes the scripts in '/etc/cron.hourly' etc.,
> calls something called 'checkproc' on each script before invoking it. 
> 'checkproc' tries to figure out if the process that the script starts is
> already running; if so, 'run-crons' skips over the script.  (I guess the
> point is to let people start long-running daemons using 'cron', which sounds
> just as strange to me as it does to you, but anyway...)  What was happening
> was that the script that makes the 'frequent' snapshots was being started at
> about the same moment as 'run-crons', and since they both invoke
> 'zfs-auto-snapshot', which was running already, 'run-crons' would skip the
> hourly script.
>
> Possible solutions include:
>
> offset the times at which the 'frequent' snapshots are taken, so it doesn't
> happen right on the hour
> edit 'run-crons' so it doesn't call 'checkproc' at all
> edit 'run-crons', adding 'sleep 10' near the top, to let the previous
> 'zfs-auto-snapshot' have plenty of time to complete
>
> I went with (3), as it seemed safer than (2).
>
> I'm not sure you should do anything about this in the code of
> 'zfs-auto-snapshot', but it might be worth a mention in the README, or a
> separate README.SuSE.
>
> Oh, there was one other problem.  I have 'zfs' installed in
> '/usr/local/sbin'.  This necessitated setting the PATH explicitly in the
> 'hourly' etc. scripts so that 'zfs-auto-snapshot' could find it.  (Maybe I
> should have just added '/usr/local/sbin' to the PATH line in
> '/etc/crontab'.)  Again, this seems like it might deserve a mention in the
> README.
>
> -- Scott

**Comment by dajhorn** [comment]
Over the past year, interest in SuSE has been low, so I'm closing this ticket as stale.

**Comment by vampywiz17** [comment]
@dajhorn 

Hello there,

I'm also affect this problem and not clear to me, how to fix it... 

Now i set "frequent" to daily usage (it is my plan) but it would be good to use the official way.

**Comment by dajhorn** [comment]
> @dajhorn
> 
> Hello there,
> 
> I'm also affect this problem and not clear to me, how to fix it...
> 
> Now i set "frequent" to daily usage (it is my plan) but it would be good to use the official way.

Hi @vampywiz17, I don't work on this package anymore, and this ticket is nearly ten years old. 

You should create a new support request or ask about this issue in various other ZFS support channels.
