### ISSUE TITLE
/bin/sh: 1: zfs-auto-snapshot: not found

### ISSUE THREAD

**Issue by TheLQ** [zfsonlinux/zfs-auto-snapshot#46]
My email is filled with this error message from the frequent script. I'm running Debian (Proxmox) 

Adding /usr/local/sbin to the path fixes the issue

**Comment by dajhorn** [comment]
@TheLQ, any system that lacks `/bin/sh` is unsupported. Given that Debian (and its Proxmox flavor) link `/bin/sh` to a standard POSIX-compatible shell by default, this system needs a repair.

**Comment by FransUrbo** [comment]
> @TheLQ, any system that lacks /bin/sh is unsupported. Given that Debian (and its Proxmox flavor) link /bin/sh to a standard POSIX-compatible shell by default, this system needs a repair.
> 
From what I understand of the issue title, it's not /bin/sh it can't find, it is "zfs-auto-snapshot" (which is probably installed in /usr/local/sbin).

@TheLQ, is it cron that complains? Did you just add "zfs-auto-snapshot" in the crontab (or who/what is it supposed to run from), or did you specify the full path and name of the script (/usr/local/sbin/zfs-auto-snapshot.sh - path and suffix)?

**Comment by dajhorn** [comment]
@FransUrbo, if so, then this ticket is a duplicate of #14 or #23.  Patches welcome. Packaging welcome.

**Comment by erkannt** [comment]
I just ran into this same issue under Debian jessie.

As @dajhorn wrote in #14 there is an inconsistent behaviour where scripts in cron.d/ don't get the PATH that is defined in /etc/crontab and it therefore has to be set explicitely in the script.

Is there a reason why one couldn't simply extend the PATH in zfs-auto-snapshot.cron.frequent to something more inclusive like this:

`PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"`
