### ISSUE TITLE
Pull requests ignored

### ISSUE THREAD

**Issue by rkarlsba** [zfsonlinux/zfs-auto-snapshot#60]
Seems pull requests on this one are all ignored, which is quite annoying. Who is responsible for this thing? If noone wants it, I can take over

**Comment by mailinglists35** [comment]
>  If noone wants it, I can take over

It would be AWESOME if you have time to maintain a fork integrating most needed patches.
There are not just the PR here, but there are also lots of forks (look in the upper right corner near the "Fork" button, it says 89) with their own patches
https://github.com/zfsonlinux/zfs-auto-snapshot/network

**Comment by highvoltage** [comment]
Hi, I just joined the project and will be closing/merging as many of the PRs as possible over the next week or so. Feel free to contact me too via my email address listed on my github profile page.
