### ISSUE TITLE
Recursion doesn't work where a sibling / child has com.sun:auto-snapshot=false

### ISSUE THREAD

**Issue by attie** [zfsonlinux/zfs-auto-snapshot#80]
When a child or sibling has `com.sun:auto-snapshot=false`, none of it's cohort receive snapshots when requested by `--recursive` - only the root provided.

Setup involves a filesystem that does not want auto-snapshot, while its neighbour does:
```
$ truncate -s 64M pool
$ zpool create test $(pwd)/pool
$ zfs create test/child1
$ zfs create test/child2
$ zfs set com.sun:auto-snapshot=true test
$ zfs set com.sun:auto-snapshot=false test/child2
$ zfs get -r com.sun:auto-snapshot test
NAME         PROPERTY               VALUE                  SOURCE
test         com.sun:auto-snapshot  true                   local
test/child1  com.sun:auto-snapshot  true                   inherited from test
test/child2  com.sun:auto-snapshot  false                  local
```

`child2` could be at any depth (my use-case is much deeper), and prevents _all_ other filesystems under the given root from receiving a snapshot.

Now, try to make a recursive snapshot - expecting `test` and `test/child1` to be covered, with `test/child2` excluded:
```
$ zfs-auto-snapshot -vnd --recursive test
Debug: Including test for regular snapshot.
zfs snapshot -o com.sun:auto-snapshot-desc='-'  'test@zfs-auto-snap-2017-12-29-1834'
@zfs-auto-snap-2017-12-29-1834, 1 created, 0 destroyed, 0 warnings.
```
As can be seen, we only get a snapshot for `test`, while `test/child1` (silently) does not receive one.
Note: "_Including test for **regular** snapshot_" and `zfs snapshot` without `-r`

If you remove `child2`'s `com.sun:auto-snapshot=false`, and try again:
```
$ zfs inherit com.sun:auto-snapshot test/child2
$ zfs-auto-snapshot -vnd --recursive test
Debug: Including test for recursive snapshot.
zfs snapshot -o com.sun:auto-snapshot-desc='-' -r 'test@zfs-auto-snap-2017-12-29-1834'
@zfs-auto-snap-2017-12-29-1834, 1 created, 0 destroyed, 0 warnings.
```
Success, however now `test/child2` is included in the snapshot
Note: "_Including test for **recursive** snapshot_" and `zfs snapshot -r`.

This is due to the test on [zfs-auto-snapshot:498](https://github.com/zfsonlinux/zfs-auto-snapshot/blob/277287f8241b069fc030267f1899837be4e6f77b/src/zfs-auto-snapshot.sh#L498).

---

I understand that this is due to the use of `zfs snapshot -r`, which would create a snapshot on the unwanted filesystem... and I'm not sure what to suggest aside from (at the very least) a WARNING / NOTE printed at runtime to make this point clear.

Are snapshots cheap enough to create one on `test/child2` as a side effect of `zfs snapshot -r`, to then go back and tidy up the unwanted snapshot?

It would be a shame to lose the atomic nature of `zfs snapshot -r` by splitting into multiple calls... but we could potentially unroll the recursion and architect the following (though command line length could be an issue for large systems):
```
zfs snapshot test@${SNAPNAME} test/child1@${SNAPNAME}
```

**Comment by riyad** [comment]
@attie as you rightly pointed out the root of the recursive datasets is put into the "regular" snapshot list because `zfs snapshot -r` will not honor the  `com.sun:auto-snapshot=false` property.
I've currently created PR #85 which uses the solution you describe last. I.e. making multiple (read non-atomic) snapshots.

**Comment by riyad** [comment]
BTW using `//` would produce a bunch of non-atomic snapshots also.

**Comment by attie** [comment]
Interesting, please could you expand on use of `//`?

**Comment by riyad** [comment]
`//` is `zfs-auto-snapshot`'s way of saying "all filesystems" (see [man page](https://github.com/zfsonlinux/zfs-auto-snapshot/blob/master/src/zfs-auto-snapshot.8#L89))

e.g. `zfs-auto-snapshot --quiet --syslog --label=daily --keep=31 //` from the [daily cron file](https://github.com/zfsonlinux/zfs-auto-snapshot/blob/master/etc/zfs-auto-snapshot.cron.daily#L6)

**Comment by kpande** [comment]
you can do atomic snapshots without `-r` using zfs channel programmes, this script is basically obsolete and should gracefully die already

**Comment by riyad** [comment]
@kpande not everyone has the newest version on ZFS :cry: (e.g. [Ubuntu is still on 0.6.5](https://packages.ubuntu.com/artful/zfsutils-linux))

**Comment by attie** [comment]
Thanks for the explanation @riyad - one of the big reasons I'm looking forward to Bionic!

**Comment by darkpixel** [comment]
This just bit me with 0.6.5 on Ubuntu.
All my boxes are calling ```/usr/local/bin/zfs-auto-snapshot.sh --quiet --syslog --label=frequent --recursive --keep=16 rpool```

It's only doing a snapshot of ```rpool``` and none of the underlying datasets--apparently because of ```rpool/swap```.

If I change the command from:
```/usr/local/bin/zfs-auto-snapshot.sh --quiet --syslog --label=frequent --recursive --keep=16 rpool```
to:
```/usr/local/bin/zfs-auto-snapshot.sh --quiet --syslog --label=frequent --recursive --keep=16 //```

I get snapshots as expected.  I don't really care about atomicity, but it was a nice surprise to find our mailstore hadn't been getting snapshots for 2 years. :)

I better get the box upgraded.
