### ISSUE TITLE
'//' only takes snapshot of the first

### ISSUE THREAD

**Issue by jornodberg** [zfsonlinux/zfs-auto-snapshot#87]
Hi.

I have been using zfs-auto-snapshot on a server for quite a while, and it's been working great.
Now I converted to zfs on another linux box, and downloaded zfs-auto-snapshot from this git again.

This newer version only took snapshot of the first partition.

My layout is like this, on Ubuntu 16.04 x64:
HDRAID/partimag            13,2G  3,86T  13,2G  /home/partimag
SSD                        99,5G   125G    96K  /
SSD/ROOT                   45,1G   125G  43,9G  /
SSD/SWAP                   4,25G   130G    64K  -
SSD/home                   49,5G   125G  49,5G  /home

But only "SSD/ROOT" was taken snapshot of, when run from cron ( zfs-auto-snapshot --quiet --syslog --label=frequent --keep=4 // )

So I copied over the earlier version from my other server - and everything was taken snapshots of.

I can't find any version-string in the script, so I'm unsure of how I can help to solve this....

**Comment by jornodberg** [comment]
I ran a diff on the two files, so I'll provide that here:

`< 			test -n "$opt_verbose" && echo $*
---
> 			test -z ${opt_quiet+x} && test -n "$opt_verbose" && echo $*
194c194
< 					if do_run "zfs destroy $FLAGS '$jj'" 
---
> 					if do_run "zfs destroy -d $FLAGS '$jj'" 
370,371c370,371
< ZFS_LIST=$(env LC_ALL=C zfs list -H -t filesystem,volume -s name \
<   -o name,com.sun:auto-snapshot,com.sun:auto-snapshot:"$opt_label") \
---
> ZFS_LIST=$(env LC_ALL=C zfs list -r -H -t filesystem,volume -s name \
>   -o name,com.sun:auto-snapshot,com.sun:auto-snapshot:"$opt_label" "${@}") \
376c376,380
< 	SNAPSHOTS_OLD=$(env LC_ALL=C zfs list -H -t snapshot -o name -s name|grep $opt_prefix |awk '{ print substr( $0, length($0) - 14, length($0) ) " " $0}' |sort -r -k1,1 -k2,2|awk '{ print substr( $0, 17, length($0) )}') \
---
> 	SNAPSHOTS_OLD=$(env LC_ALL=C zfs list -r -H -t snapshot -o name -s name "${@}" | \
> 		grep $opt_prefix | \
> 		awk '{ print substr( $0, length($0) - 14, length($0) ) " " $0}' | \
> 		sort -r -k1,1 -k2,2 | \
> 		awk '{ print substr( $0, 17, length($0) )}') \
379c383
< 	SNAPSHOTS_OLD=$(env LC_ALL=C zfs list -H -t snapshot -S creation -o name) \
---
> 	SNAPSHOTS_OLD=$(env LC_ALL=C zfs list -r -H -t snapshot -S creation -o name "${@}" ) \
439c443,444
< 	# Exclude datasets that are not named on the command line.
---
> 
>         # Exclude datasets that are not named on the command line.`

**Comment by vrivellino** [comment]
I think #82 is the culprit.

I ran into the same problem. I checked out the repo at 1ae1adc5f088b608682d2d525b7cb5337f693ac3 and that seems to be working.

**Comment by sdenovan** [comment]
Duplicated here as well. This is a serious issue because it fails to create snapshots and generates no errors -- leaving users completely unaware that the automatic snapshots are not being made.

The issue is the introduction of "${@}" at the end of the definition for ZFS_LIST which becomes "//". It's the difference between:

**CURRENT / WRONG**
zfs list -t filesystem,volume //

**CORRECT**
zfs list -t filesystem,volume
